### ISSUE TITLE
Wezterm does not support Wayland and should probably be removed from this list for the time being.

### ISSUE THREAD

**Issue by pallaswept** [natpen/awesome-wayland#101]
I gave it a shot since it's on the list, and had major problems. Checking the issues list there are several regarding Wayland and the author specifically says that Wayland support should be disabled.

See for example:

https://github.com/wez/wezterm/issues/4312#issuecomment-1724570465
https://github.com/wez/wezterm/issues/3214#issuecomment-1702029816

> There are numerous open wayland related issues filed here against wezterm. ....
> Unfortunately, the underlying wayland ecosystem crates dramatically changed their APIs (for the better!) which will make that effort essentially a rewrite of wayland support in wezterm. That should happen, but I just can't justify spending so much of my precious downtime on something that I don't use....
> In the meantime, what I recommend, if you're dead-set on using a wayland compositor, is using XWayland by setting enable_wayland=false in your wezterm configuration.

**Comment by jokeyrhyme** [comment]
It does support Wayland and I've been using wezterm happily for over a year across GNOME, sway, river, and even COSMIC

I've even worked with wez to debug and file PRs to improve the Wayland support in a few places

**Comment by pallaswept** [comment]
> It does support Wayland

Wez said it doesn't - to reiterate the quote above from him:

>  I recommend... enable_wayland=false

**Comment by pallaswept** [comment]
Sorry, I'm not trying to be short with you, was just trying to stick to the point; but it felt rude so I'll reply to your whole post (at risk of feeling argumentative which is why I was trying to stick to the point haha)....

> It does support Wayland 

Sometimes it does, but for a great many people, it doesn't. If you follow the links I gave above, then follow the links from those, and the links from those, you'll have a few dozen Wayland-specific issues open in your browser.

> and I've been using wezterm happily for over a year across GNOME, sway, river, and even COSMIC

And many others have tried it and found it unusable within seconds - like me, which is sad, because I really liked a lot about it. It's the _only_ terminal emulator I could find which had scrollbars, window management, and supported OSC52 for use with clipboard managers. So I will have to take a second-best alternative which is going to probably be foot+tmux, I'm currently using kitty, which has all that minus scrollbars, and its lack of scrollbars is a real UX shortcoming. Foot has the scrollbars and OSC52 but no window management, so I'll have to add tmux to that to get the job done. Wezterm could have done it all, out of the box, but....

It was unusably laggy when typing into it, meaning like as in, I'd type, and then several whole seconds later I'd see my text appear. I figured there might be some kind of fix for it so I went to check and what I found was a mass of reports of problems with it on Wayland, and the author literally saying, don't use Wayland, it doesn't work.

> I've even worked with wez to debug and file PRs to improve the Wayland support in a few places

Legendary. Thanks for your efforts and I hope to try it again another time. But for now, it doesn't run properly on Wayland, and I need to use Wayland.

**Comment by jokeyrhyme** [comment]
The description text of this list is not "a list of projects that work 100% without bugs under wayland for 100% of users", so I would suggest that this is not reasonable criteria

Many of the projects on the list have some wayland bugs in their issue trackers, does that mean we should delete them, too?

**Comment by pallaswept** [comment]
> The description text of this list is not "a list of projects that work 100% without bugs under wayland for 100% of users", so I would suggest that this is not reasonable criteria

You make a good point about whether these issues meet the criteria for having this on the list, but you're overplaying it with the whole "works 100% for 100% of people". The author specifically saying that he recommends wayland users disable wayland support is a long, long way from 100%. This is officially 0% supported. Of course,, it probably works a _lot_ more than that in reality, but the fact is, Wayland is officially not supported by this application. 

But I mean what I say, you make a good point, so I went to look for the criteria, because I'll close this issue myself if the app meets the criteria. as it happens, I couldn't find a criteria as such, but the closest thing I could find was what's on the contributing page. It says:

> Our goal is to have mostly projects that are stable and useful to many users.

This is definitely not stable on wayland, to many users. The author himself said that if you "insist" on using a Wayland compositor, to disable it in the app.

But, there's also this:
> is the entry valuable to people trying to get things done in Wayland?

And I'd argue that for people trying to get things done in Wayland, this could definitely be valuable. So, sure, it meets tht criteria.

But finally, there's this:

> [Removing projects](https://github.com/natpen/awesome-wayland/blob/master/CONTRIBUTING.md#removing-projects)
> We don't remove projects unless they are outright broken or pronounced deprecated by another project or by its author.

This has been pronounced outright broken on Wayland by its author. So it might maybe meet the criteria for being on the list, but it definitely meets the criteria for removal.

> Many of the projects on the list have some wayland bugs in their issue trackers, does that mean we should delete them, too?

Again, you're overplaying a good point, to the point of hyperbole. This isn't just "some bugs", it's a large collection of bugs effecting a large group of users and that's why it's officially unsupported. If the applications on this list are officially unsupported on Wayland then yes, I think they should be removed, too. You can hardly call it "awesome" if it isn't even supposed to work.

Perhaps, the app should stay on the list, but with a note added to warn users that Wayland is not officially supported and they may experience bugs? I think that's the least that should be done. I trust the "Awesome Wayland" list to give me "awesome wayland", and today it messed up my machine. I'm sure that's not the intention of this list.

**Comment by pallaswept** [comment]
> I trust the "Awesome Wayland" list to give me "awesome wayland", and today it messed up my machine. 

I'm totally not glued to the idea of removing this (hopefully that's obvious from the title and our discussion) and obviously you understand why I would want to avoid this experience for others, and you're keen on the app staying in the list, do you have any suggestions to help alleviate the problem? Do you like the idea of maybe adding some kind of warning or something? Let's talk together about a good solution :)

**Comment by jokeyrhyme** [comment]
From the comments in the linked issues and others, it still looks as though users will likely encounter issues with all sorts of applications if they are trying to use wayland with nVidia hardware

So, rather than individually mark each of dozens of apps that will likely have issues on nVidia chips, perhaps a general disclaimer at the top of the list? But, I'm not sure it's the purpose of this list to be a general status page for wayland in general :shrug:

**Comment by pallaswept** [comment]
> From the comments in the linked issues and others, it still looks as though users will likely encounter issues with all sorts of applications if they are trying to use wayland with nVidia hardware

Nope, just this so far, and ironically, nvidia's own settings program which is still X-specific. But it's not on a Wayland list and I didn't expect it to work under wayland anyway.

> So, rather than individually mark each of dozens of apps that will likely have issues on nVidia chips

Yeh we;re not talking about problems with nvidia or any other apps here, we're talking about problems with wezterm. We're just looking for a way to avoid the bad experience I had with wezterm. You're welcome to file another issue for nvidia-specific problems but I'm not trying to solve that problem, I'm trying to solve this one. Can you, also, please?

**Comment by jokeyrhyme** [comment]
> Yeh we;re not talking about problems with nvidia or any other apps here, we're talking about problems with wezterm. 

Your original post links to this comment https://github.com/wez/wezterm/issues/3214#issuecomment-1702029816 which specifically addresses the topic of wezterm behaviour in wayland on nVidia hardware, where the author of wezterm recommends that users with that combination switch to Xwayland or X11

> I'm trying very hard to keep this conversation productive and solve a real problem I had so others don't have to suffer it, and it seems like you just want to argue.

I don't want to argue with you, but we have conflicting beliefs:

- I believe that my (good) experience is representative of the majority of users, and that there's little harm encountering an issue and moving on to the next solution, and that there's great benefit for both the wayland and wezterm communities to be sharing ideas and experiences

- you seem to believe that your (bad) experience is representative of the majority of users, and that your bad experience is so terrible that future users must be protected from this, because users are incapable of deciding for themselves whether an item on a list serves their own personal use cases or not

Unless we can change each others minds about the above, there's probably no more to say on the subject

**Comment by pallaswept** [comment]
> > Yeh we;re not talking about problems with nvidia or any other apps here, we're talking about problems with wezterm.
> 
> Your original post links to this comment [wez/wezterm#3214 (comment)](https://github.com/wez/wezterm/issues/3214#issuecomment-1702029816) which specifically addresses the topic of wezterm behaviour

YES, WEZTERM behaviour. Emphasis on WEZTERM. For the last time, we are not talking about nvidia here, we are talking about how to make sure that users who read this list, don't try wezterm and have a bad time because wayland is not supported by that application and can break if they try it.

> in wayland on nVidia hardware, where the author of wezterm recommends that users with that combination switch to Xwayland or X11
 
If you read other threads you'll see he specifically says it's not supported, without any reference to hardware. And if you read that entire post he actually says that users who insist on using WAYLAND - not nvidia, just wayland - disable it in the application. A good 70-80% of that post discusses wayland and not nvidia, only the first two lines reference the hardware.
 

> > I'm trying very hard to keep this conversation productive and solve a real problem I had so others don't have to suffer it, and it seems like you just want to argue.
> 
> I don't want to argue with you,

The evidence is to the contrary.

>  but we have conflicting beliefs:
> 
>     * I believe that my (good) experience is representative of the majority of users, 

First you say it's an nvidia problem - the hardware used by the majority of users..... Then you say that it's fine for the majority of users. And you say you're not trying to argue. Dude, you are STRUGGLING to argue.

> and that there's little harm encountering an issue and moving on to the next solution

You don't get to decide what's good enough for my computer or anyone else's.

>, and that there's great benefit for both the wayland and wezterm communities to be sharing ideas and experiences

And nothing I've said has opposed that.

>     * you seem to believe that your (bad) experience is representative of the majority of users,

Never mind that I said

> it probably works a lot more than that in reality

But of course, you're not actually reading or thinking about what I'm saying, you're just arguing.

> and that your bad experience is so terrible that future users must be protected from this, 

Absolutely they should. I'm not in the habit of letting people fall into the same traps I have, because I'm not an asshole.

> because users are incapable of deciding for themselves whether an item on a list serves their own personal use cases or not

If this were a list of "decide if it suits your use case or not" it'd include every app ever made. You're so far from making sense it's just bonkers.


> Unless we can change each others minds about the above, there's probably no more to say on the subject

There's no changing your mind, you're biased because you're a contributor and don't actually care about the experience of people who visit this list. I've got no dog in this fight other than looking out for those people.

We're done here.

**Comment by pallaswept** [comment]
The author's words on Wayland support in Wezterm (bold emphasis is mine) are all I have to say on this matter:

>My personal position on wayland is that it is still immature compared to X11, even on AMD hardware. I run X11 because I don't have time to put up with it. I understand that wayland is the future, it just isn't the present, for me....
> There are numerous open wayland related issues filed here against wezterm. ....
> Unfortunately, the underlying wayland ecosystem crates dramatically changed their APIs (for the better!) which will make that effort essentially a rewrite of wayland support in wezterm. That should happen, but I just can't justify spending so much of my precious downtime on something that I don't use....
> In the meantime, **what I recommend, if you're dead-set on using a wayland compositor, is using XWayland by setting enable_wayland=false in your wezterm configuration.**

This meets the criteria set for removal from the list. I'm going to unsubscribe because I have better things to do with my sunday night than deal with fanboy trolls, like setting up my new terminal.

**Comment by pallaswept** [comment]
https://github.com/natpen/awesome-wayland/issues/102
