### ISSUE TITLE
Polkit

### ISSUE THREAD

**Issue by FcoMarcosMAbreu** [natpen/awesome-wayland#50]
Please, include instructions about how to intagrate Polkit. For example, launch a vm in Virt-Manager don't work.

**Comment by natpen** [comment]
Sorry, I'm a bit confused by this issue. I just looked up Polkit and it doesn't seem wayland-specific, or even wayland-related. And apart from that, even if it were wayland-specific, there's also the fact that this repo doesn't include instructions for anything - it's simply a place to link out to projects.

I would suggest you repost your question/issue in the [Polkit repository itself](https://gitlab.freedesktop.org/polkit/polkit/-/issues)!

**Comment by FcoMarcosMAbreu** [comment]
Ok. I did a mess.
