### ISSUE TITLE
Looking for a terminal emulator that's also a compositor

### ISSUE THREAD

**Issue by vanfanel** [natpen/awesome-wayland#82]
Hello there

I absolutely love this repository, since I am right now building my dream Wayland-based system from (almost) scratch.

I am a command console addict, so I am looking for a wayland-compatible terminal emulator that doesn't need a compositor. Does such a thing exist? I am almost sure I have read something like that... But I can't find it anymore.

I know Weston includes weston-terminal, but that's not what I am looking for: imagine running "foot" without Weston. My idea would be something like a TTY... but on Wayland.

Thanks!

**Comment by b-** [comment]
Are you looking for a graphical terminal emulator that doesn't require a GUI/display server?  (If so, see https://github.com/Aetf/kmscon)

I'm not understanding how Wayland fits into the picture if you don't want a compositor, or at least if you don't want a separate one.

**Comment by vanfanel** [comment]
@b- KMSCON would be ideal if it wasn't dead as a Dodo.
