### ISSUE TITLE
Add Clight as a way to control both backlight and gamma

### ISSUE THREAD

**Issue by FedeDP** [natpen/awesome-wayland#83]
Hi! 
I am the dev of [Clight](https://github.com/FedeDP/Clight); it is a tool that manages screen backlight capturing ambient light from:
* webcam
* ambient light sensors

Moreover, it is able to manage keyboard backlight, dimming, dpms and gamma temp.
I think it would be a great addition to the list, given that it supports wayland :) 
Thank you!

**Comment by natpen** [comment]
I think so too! Please feel to open a pull request and I'll accept.
