### ISSUE TITLE
remove blue-recorder

### ISSUE THREAD

**Issue by colemickens** [natpen/awesome-wayland#87]
literally the first line of code force use of X.

I just spent 20 minutes packaging this and really wish I hadn't. I don't think it belongs on this list.

**Comment by colemickens** [comment]
https://github.com/xlmnxp/blue-recorder/blob/9b4ec9bb05f794043c38c7a9ef5de0203948288b/src/main.rs#L31

**Comment by natpen** [comment]
Thank you for the flag. I've been away from this repository for quite a while, but I'm removing it now!
